### PR TITLE
[sailfish-qdoc-template] Add left margin. JB#57817

### PR DESCRIPTION
**Pull request by vigejolla**

### CODE REVIEW

**Comment by martyone** [comment]
How does it look with the viewers where the border was not missing? Please remind be whether we use other viewers nowadays :)

**Comment by vigejolla** [comment]
> How does it look with the viewers where the border was not missing? Please remind be whether we use other viewers nowadays :)

SDK 3.7.4:

sdk-374

SDK 3.10.1 without the added margin:

without_margin

SDK 3.10.1 with the added margin:

with_margin

**Comment by vigejolla** [comment]
To my knowledge we don't use any other viewers

**Comment by martyone** [comment]
hm, wouldn't it be more future-proof to add the margin to the widget instead? That is closer to where the issue actually exists anyway, isn't it?

**Comment by vigejolla** [comment]
> hm, wouldn't it be more future-proof to add the margin to the widget instead? That is closer to where the issue actually exists anyway, isn't it?

In my opinion it makes more sense to try to follow what Qt has done with their docs. Of course, this is just a small part of that, there's still plenty to do if want to get our docs as good looking. But this task was just about the margin, and it's done here.

**Comment by vigejolla** [comment]
> 



> In my opinion it makes more sense to try to follow what Qt has done with their docs.

Of course I did a lousy job at that. I now realize I should have just changed the "margin-left" in body from 0.5em to 5px. *That's* what they did. I somehow wasn't paying enough attention.

**Comment by martyone** [comment]
If the margin is added in upstream, then there is no question about :)

**Comment by vigejolla** [comment]
> If the margin is added in upstream, then there is no question about :)

It is, but like I wrote above, I added it wrong. I'll update the PR shortly.

**Review by martyone — APPROVED** [review]

**Pull request merged**
